apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ticketing/auth
      context: .
      docker:
        dockerfile: packages/auth/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .